//! Ex command type definitions.

/// All supported Ex commands.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ExCommand {
    Quit,
    ForceQuit,
    QuitAll,
    ForceQuitAll,
    Write(Option<String>),
    WriteQuit(Option<String>),
    WriteAll,
    Edit(String, bool),
    BufferList,
    BufferNext,
    BufferPrev,
    BufferDelete(bool),
    Split,
    VSplit,
    New,
    VNew,
    Only,
    Set(String),
    GoToLine(usize),
    ShellCommand(String),
    FilterCommand(String, String),
    Substitute(String, String, String),
    Global(String, String),
    VGlobal(String, String),
    Enew,
    SaveAs(String),
    SwitchBuffer(u64),
    ScratchBuffer,
    Marks,
    Registers,
    Jumps,
    Changes,
    Digraphs,
    FileInfo,
    Sort,
    NoHlSearch,
    CNext,
    CPrev,
    COpen,
    Messages,
    Source(String),
    Execute(String),
    Normal(String),
    SyntaxCmd(String),
    Highlight(String),
    Map(String),
    Unmap(String),
    MapClear,
    AutoCmd(String),
    Delete(Option<String>),
    Yank(Option<String>),
    Copy(Option<String>, String),
    Move(Option<String>, String),
    Read(String),
    Put(Option<char>),
    FileType(String),
    Cd(String),
    Pwd,
    MkSession(Option<String>),
    OldFiles,
    Explorer,
    Terminal,
    Find,
    LiveGrep,
    UndoTree,
}

impl ExCommand {
    /// Human-readable name of the command.
    pub fn name(&self) -> &'static str {
        match self {
            Self::Quit => "quit",
            Self::ForceQuit => "quit!",
            Self::QuitAll => "quitall",
            Self::ForceQuitAll => "quitall!",
            Self::Write(_) => "write",
            Self::WriteQuit(_) => "wq",
            Self::WriteAll => "wall",
            Self::Edit(..) => "edit",
            Self::BufferList => "ls",
            Self::BufferNext => "bnext",
            Self::BufferPrev => "bprev",
            Self::BufferDelete(_) => "bdelete",
            Self::Split => "split",
            Self::VSplit => "vsplit",
            Self::GoToLine(_) => "goto",
            Self::Set(_) => "set",
            Self::Substitute(..) => "substitute",
            Self::Global(..) => "global",
            Self::VGlobal(..) => "vglobal",
            _ => "command",
        }
    }
}
