//! :mksession and :source command handlers.

use crate::editor::EditorState;

impl EditorState {
    /// Handle :mksession [file] — save session file.
    pub(crate) fn handle_mksession(&mut self, path: Option<&str>) {
        let path = path.unwrap_or("Session.vim");
        let mut lines = Vec::new();
        lines.push("\" Session file generated by kjxlkj".to_string());
        // Save buffer list.
        for buf in self.buffers.iter() {
            if let Some(ref p) = buf.path {
                lines.push(format!("edit {}", p.display()));
            }
        }
        let content = lines.join("\n") + "\n";
        match std::fs::write(path, content) {
            Ok(()) => self.notify_info(&format!("Session saved: {path}")),
            Err(e) => {
                self.notify_error(&format!("E138: Cannot write: {e}"));
            }
        }
    }

    /// Handle :source {file} — read and execute commands.
    pub(crate) fn handle_source(&mut self, path: &str) {
        let content = match std::fs::read_to_string(path) {
            Ok(c) => c,
            Err(e) => {
                self.notify_error(&format!("E484: {path}: {e}"));
                return;
            }
        };
        for line in content.lines() {
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed.starts_with('"') {
                continue;
            }
            self.execute_ex_command(trimmed);
        }
    }
}
