//! Editor state aggregation and snapshot production.

mod action_dispatch;
mod action_dispatch2;
pub mod after_dir;
pub mod audio;
pub mod auto_session;
pub mod autocmd;
mod buffer;
pub mod buffer_options;
#[cfg(test)]
mod buffer_tests;
pub mod cjk_support;
mod command_dispatch;
mod command_dispatch_ext;
mod command_dispatch_tabs;
mod command_parse;
pub mod completion;
pub mod dap;
pub mod digraphs;
mod editor;
mod editor_actions;
mod editor_actions2;
mod editor_actions3;
mod editor_auto_marks;
mod editor_auto_pairs;
mod editor_changelist;
mod editor_char_ops;
mod editor_cmdline;
mod editor_comments;
mod editor_config;
mod editor_file_ops;
mod editor_global_sort;
mod editor_init;
mod editor_insert;
mod editor_jumplist;
mod editor_key_dispatch;
mod editor_macros;
mod editor_marks;
mod editor_op_resolve;
mod editor_operators;
mod editor_quickfix;
mod editor_range_cmds;
mod editor_range_dispatch;
mod editor_range_parse;
mod editor_scroll;
mod editor_search_ops;
mod editor_shell;
mod editor_snapshot;
mod editor_substitute;
pub mod editor_tabs;
pub mod editor_types;
mod editor_window_adv;
mod editor_window_ops;
mod editor_window_resize;
pub mod file_explorer;
pub mod filetype;
pub mod flash_jump;
pub mod floating;
pub mod folds_advanced;
pub mod git_features;
pub mod ime;
pub mod keybinding_dsl;
pub mod line_wrap;
pub mod live_grep;
pub mod lsp_features;
pub mod mappings;
pub mod mouse;
pub mod multicursor;
pub mod notifications;
pub mod persistence;
pub mod popup;
pub mod regex_engine;
pub mod remote;
pub mod search;
mod session;
pub mod session_features;
pub mod snippets;
pub mod spell;
pub mod statusline_dsl;
pub mod tags;
pub mod text_object_function;
pub mod theming;
pub mod tmux;
pub mod treesitter_objects;
pub mod unicode_input;
pub mod user_commands;
pub mod user_functions;
pub mod view_management;
mod viewport;
mod window;
pub mod window_layouts;
pub mod wm_integration;

pub use buffer::{BufferState, LineEnding};
pub use command_dispatch::dispatch_command;
pub use editor::EditorState;
pub use editor_types::{MarkEntry, QuickfixEntry};
pub use session::{load_session, save_session, SessionData, SessionLayout};
pub use viewport::ViewportState;
pub use window::{WindowContent, WindowOptions, WindowState};

/// Convert char to RegisterName.
pub(crate) fn register_name_from_char(c: char) -> Option<kjxlkj_core_types::RegisterName> {
    kjxlkj_core_types::RegisterName::from_char(c)
}
