" Session file generated by kjxlkj
edit test.txt
call cursor(1, 1)
set autoindent=true
set autosaveinterval=5
set expandtab=false
set filetype=text
set formatoptions=tcq
set hlsearch=true
set ignorecase=false
set incsearch=true
set number=false
set relativenumber=false
set scrolloff=0
set shiftwidth=8
set smartcase=false
set tabstop=8
set textwidth=79
set wrap=true
b test.txt
