//! Web handlers

pub mod admin;
pub mod assets;
pub mod discoverability;
pub mod favorites;
pub mod health;
pub mod history;
pub mod home;
mod http;
pub mod login;
pub mod logout;
pub mod media;
pub mod media_attachments;
mod media_derivatives;
mod media_input;
mod media_insert;
mod media_support;
mod note_media_input;
pub mod password_reset;
pub mod popular_sections;
pub mod preview;
pub mod resource;
pub mod resource_file;
pub mod resource_history;
mod resource_payload;
pub mod resources;
pub mod search;
pub mod session;
pub mod settings;
mod settings_input;
pub mod setup;
pub mod site_icon;
