//! UI model types for kjxlkj editor.
//!
//! This crate defines UI snapshot structures for rendering.

mod buffer_view;
mod colorcolumn;
mod completion;
mod completion_item;
mod completion_kind;
mod completion_source;
mod conceal;
mod conceal_types;
mod cursor;
mod cursor_blink;
mod cursorhl;
mod diffhl;
mod diffhl_types;
mod dimensions;
mod float_state;
mod float_types;
mod fold;
mod gutter;
mod gutter_types;
mod highlight;
mod indent;
mod layout;
mod layout_node;
mod listchars;
mod matchpairs;
mod number;
mod popup;
mod popup_item;
mod scroll;
mod searchhl;
mod sign;
mod sign_types;
mod snapshot;
mod spelling;
mod spelling_types;
mod status;
mod status_segment;
mod terminal;
mod terminal_buffer;
mod viewport;
mod virtual_text;
mod virtual_text_types;
mod wrap;

pub use buffer_view::BufferView;
pub use colorcolumn::ColorColumn;
pub use completion::CompletionState;
pub use completion_item::CompletionItem;
pub use completion_kind::CompletionKind;
pub use completion_source::{SourceConfig, SourceKind, SourceManager, SourcePriority};
pub use conceal::ConcealState;
pub use conceal_types::{ConcealLevel, ConcealRegion, LineConceal};
pub use cursor::{CursorAppearance, CursorBlink, CursorShape};
pub use cursorhl::{CursorColumnMode, CursorHighlight, CursorLineMode};
pub use diffhl::{DiffConfig, DiffKind, DiffMarker, DiffState, DiffSummary};
pub use dimensions::Dimensions;
pub use float_state::FloatState;
pub use float_types::{FloatAnchor, FloatBorder, FloatConfig, FloatRelative, FloatWindow};
pub use fold::{Fold, FoldMethod, FoldState};
pub use gutter::{GutterCell, GutterConfig, GutterState};
pub use highlight::{Color, HlGroup, HlGroups, TextAttr};
pub use indent::{indent_level, GuideStyle, IndentGuide};
pub use layout::Layout;
pub use layout_node::{LayoutNode, SplitDirection};
pub use listchars::{ListChars, ListMode};
pub use matchpairs::{MatchPair, MatchResult, PairMatcher, DEFAULT_PAIRS};
pub use number::{NumberColumn, NumberMode};
pub use popup::{PopupMenu, PopupState};
pub use popup_item::PopupItem;
pub use scroll::{CursorPosition, ScrollAmount, ScrollDirection, ScrollState};
pub use searchhl::{SearchHighlight, SearchMatch};
pub use sign::{Sign, SignColumn, SignDefinition, SignPriority};
pub use snapshot::EditorSnapshot;
pub use spelling::{SpellConfig, SpellError, SpellResult, SpellState, UserWordList};
pub use status::{SegmentStyle, StatusLine, StatusSegment};
pub use terminal::{TermBuffer, TermCell, TermCursor, TermSize, TermState};
pub use viewport::Viewport;
pub use virtual_text::VirtualTextState;
pub use virtual_text_types::{VirtualText, VirtualTextChunk, VirtualTextPos};
pub use wrap::{WrapMode, WrapSegment, WrapState, WrappedLine};
