//! Language keyword tables for regex-fallback highlighting.

use crate::syntax::Language;

/// Keywords per language (subset for common tokens).
pub fn keywords(lang: Language) -> &'static [&'static str] {
    match lang {
        Language::Rust => &[
            "fn", "let", "mut", "pub", "use", "mod", "struct", "enum", "impl", "trait", "for",
            "while", "loop", "if", "else", "match", "return", "self", "Self", "crate", "super",
            "where", "async", "await", "const", "static", "type", "unsafe", "extern", "ref",
            "move", "as", "in", "break", "continue",
        ],
        Language::Python => &[
            "def", "class", "if", "elif", "else", "for", "while", "return", "import", "from", "as",
            "try", "except", "finally", "with", "yield", "lambda", "pass", "break", "continue",
            "and", "or", "not", "in", "is", "None", "True", "False", "raise", "del", "global",
            "nonlocal", "assert",
        ],
        Language::JavaScript | Language::TypeScript => &[
            "function",
            "const",
            "let",
            "var",
            "if",
            "else",
            "for",
            "while",
            "do",
            "return",
            "class",
            "new",
            "this",
            "import",
            "export",
            "from",
            "default",
            "try",
            "catch",
            "finally",
            "throw",
            "async",
            "await",
            "yield",
            "switch",
            "case",
            "break",
            "continue",
            "typeof",
            "instanceof",
            "of",
            "in",
        ],
        Language::C | Language::Cpp => &[
            "if", "else", "for", "while", "do", "return", "switch", "case", "break", "continue",
            "struct", "typedef", "enum", "void", "int", "char", "float", "double", "long", "short",
            "unsigned", "signed", "const", "static", "extern", "sizeof", "union", "volatile",
            "register", "goto", "default",
        ],
        Language::Go => &[
            "func",
            "var",
            "const",
            "type",
            "struct",
            "interface",
            "map",
            "chan",
            "if",
            "else",
            "for",
            "range",
            "switch",
            "case",
            "default",
            "break",
            "continue",
            "return",
            "go",
            "defer",
            "select",
            "package",
            "import",
            "fallthrough",
            "goto",
        ],
        _ => &[],
    }
}
